version: '3.8'

services: 
  frontend:
    image: thejasrao2003/machinelearningautomation:frontend
    ports: 
      - "8051:8051"
    container_name: frontend
    networks:
      - my_network

  datapreprocessing:
    image: thejasrao2003/machinelearningautomation:datapreprocessing
    ports: 
      - "5001:5001"
    container_name: datapreprocessing
    networks:
      - my_network

  visualisation:
    image: thejasrao2003/machinelearningautomation:visualisation
    ports:
      - "5002:5002"
    container_name: visualisation
    networks:
      - my_network

  modeltraining:
    image: thejasrao2003/machinelearningautomation:modeltraining
    ports:
      - "5003:5003"
    container_name: modeltraining
    networks:
      - my_network

  hyperparametertuning:
    image: thejasrao2003/machinelearningautomation:hyperparametertuning
    ports:
      - "5004:5004"
    container_name: hyperparametertuning
    networks:
      - my_network
  
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "80:80"
    container_name: nginx
    depends_on:
      - frontend
      - datapreprocessing
      - visualisation
      - modeltraining
      - hyperparametertuning
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

