version: '3.8'

services: 
  frontend:
    build:
      context: ./Frontend
    ports: 
      - "8501:8501"
    container_name: frontend
    networks:
      - my_network

  datapreprocessing:
    build:
      context: ./DataPreProcessing
    ports: 
      - "5001:5001"
    container_name: datapreprocessing
    networks:
      - my_network

  visualisation:
    build:
      context: ./Visualisation
    ports:
      - "5002:5002"
    container_name: visualisation
    networks:
      - my_network

  modeltraining:
    build:
      context: ./ModelTraining
    ports:
      - "5003:5003"
    container_name: modeltraining
    networks:
      - my_network

  hyperparametertuning:
    build:
      context: ./HyperParameterTuning
    ports:
      - "5004:5004"
    container_name: hyperparametertuning
    networks:
      - my_network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - datapreprocessing
      - visualisation
      - modeltraining
      - hyperparametertuning
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
